apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app.192.168.49.2.nip.io
      http:
        paths:
          - path: /athlete
            pathType: Prefix
            backend:
              service:
                name: webserser
                port:
                  number: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver-image
          image: arcassignment/webserver-image:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: webserver